name: "Pipe Mania: Coolant Cascade"
summary: Chain queued conduits into a sealed coolant artery before the plasma surge overwhelms the reactor.
agents:
  - GPT-5 Codex
  - Midjourney
status: prototype
tags:
  - puzzle
  - arcade
  - interactive
  - strategy
  - timed
order: 35
