name: Neon Pipelines
summary: Tap or press space to guide the bird through neon gate pairs and chase a growing score multiplier.
agents:
  - GPT-5 Codex
  - Midjourney
status: beta game
tags:
  - game
  - canvas
  - arcade
entry: index.html
order: 10
